### ISSUE TITLE
Exception on parsing BinaryNinja's version field

### ISSUE THREAD

**Issue by bhumic** [gaasedelen/lighthouse#42]
I just tried Lighthouse with BinaryNinja(latest release) and got an error:

> Loaded Python plugin 'lighthouse'
Traceback (most recent call last):
  File "%appdata%\AppData\Roaming\Binary Ninja\plugins\lighthouse_plugin.py", line 1, in <module>
    from lighthouse.util.log import logging_started, start_logging
  File "%appdata%\AppData\Roaming\Binary Ninja\plugins\lighthouse\util\__init__.py", line 3, in <module>
    from .log import lmsg, logging_started, start_logging
  File "%appdata%\AppData\Roaming\Binary Ninja\plugins\lighthouse\util\log.py", line 5, in <module>
    from .disassembler import disassembler
  File "%appdata%\AppData\Roaming\Binary Ninja\plugins\lighthouse\util\disassembler\__init__.py", line 31, in <module>
    disassembler = BinjaAPI()
  File "%appdata%\AppData\Roaming\Binary Ninja\plugins\lighthouse\util\disassembler\binja_api.py", line 106, in __init__
    self._init_version()
  File "%appdata%\AppData\Roaming\Binary Ninja\plugins\lighthouse\util\disassembler\binja_api.py", line 116, in _init_version
    major, minor, patch = map(int, disassembler_version.split("."))
ValueError: invalid literal for int() with base 10: '1344 Personal'
Python plugin 'lighthouse_plugin' could not be loaded

The problem is that the version string is of format '1.1.1344 Personal' so I fixed with:
 `disassembler_version = binaryninja.core_version.split("-", 1)[0] if "-" in binaryninja.core_version else binaryninja.core_version.split(" ", 1)[0]`

**Comment by gaasedelen** [comment]
Uhf, good catch. I didn't have a chance to test on a personal license.

This is an easy fix, I'll merge it directly into master.

**Comment by gaasedelen** [comment]
Thanks for the report!

This should be resolved on master now (a81aa6d590bae18fe200dcde53b496fcd4311fa1)

**Comment by bhumic** [comment]
It is still broken. This should be the fix: https://github.com/bhumic/lighthouse/blob/27a373e991ea746114c26961f85e8eaf9653b751/plugin/lighthouse/util/disassembler/binja_api.py#L114-L120

**Comment by gaasedelen** [comment]
Oh gosh, what a hilarious & embarrassing commit. I clearly hadn't fully woken up when I pushed that 😬.

This should be fixed now. I also downloaded and installed Binary Ninja Personal edition so I can prevent this from happening again in the future.

Feel free to open a PR next time!
